### PR TITLE
added support for android 6

### PR DESCRIPTION
**Pull request by rahulkumar66**
add support for checking toybox since google merged toybox into aosp since android M

### CODE REVIEW

**Comment by rahulkumar66** [comment]
@Stericson any chance of merging?

**Comment by Stericson** [comment]
@rattlehead666 Just curious, why not add a new method to check for ToyBox? or two methods, one that checks for both by calling the first method and a method for finding toybox?

Providing this code here kinda makes the method name (description) misleading...

Just interested in hearing your thoughts...

**Comment by rahulkumar66** [comment]
I understand your concern but this way developers won't need to change anything in their code.

**Comment by Stericson** [comment]
Understood, merged.

**Pull request merged**
